# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Trakt' do
pod 'Alamofire', '~> 3.0'
pod 'SDWebImage', '~>3.7'
end

target 'TraktTests' do

end

target 'TraktUITests' do

end

